# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'depositAddPage.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_depositAdd(object):
    def setupUi(self, depositAdd):
        depositAdd.setObjectName("depositAdd")
        depositAdd.resize(657, 767)
        depositAdd.setStyleSheet("background-color: rgb(49, 49, 49);")
        self.groupBox = QtWidgets.QGroupBox(depositAdd)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 641, 751))
        self.groupBox.setStyleSheet("\n"
"color: rgb(200, 200, 200);")
        self.groupBox.setObjectName("groupBox")
        self.gridLayoutWidget = QtWidgets.QWidget(self.groupBox)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 20, 611, 691))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.depositBookNameEdit = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.depositBookNameEdit.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(42, 42, 42);")
        self.depositBookNameEdit.setObjectName("depositBookNameEdit")
        self.gridLayout_3.addWidget(self.depositBookNameEdit, 0, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label.setObjectName("label")
        self.gridLayout_3.addWidget(self.label, 0, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout_3.addWidget(self.label_2, 2, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout_3.addWidget(self.label_4, 5, 0, 1, 1)
        self.depositUserNameEdit = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.depositUserNameEdit.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(42, 42, 42);")
        self.depositUserNameEdit.setObjectName("depositUserNameEdit")
        self.gridLayout_3.addWidget(self.depositUserNameEdit, 2, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout_3.addWidget(self.label_3, 4, 0, 1, 1)
        self.depositBookSearchButton = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.depositBookSearchButton.setObjectName("depositBookSearchButton")
        self.gridLayout_3.addWidget(self.depositBookSearchButton, 0, 2, 1, 1)

        # Deposit book table widget
        self.depositBookTableWidget = QtWidgets.QTableWidget(self.gridLayoutWidget)
        self.depositBookTableWidget.setStyleSheet("\n"
                                                  "background-color: rgb(225, 225, 225);\n"
                                                  "color: rgb(103, 103, 103);")
        self.depositBookTableWidget.setShowGrid(True)
        self.depositBookTableWidget.setGridStyle(QtCore.Qt.SolidLine)
        self.depositBookTableWidget.setColumnCount(6)
        self.depositBookTableWidget.setObjectName("depositBookTableWidget")
        self.depositBookTableWidget.rowCount()
        self.depositBookTableWidget.setHorizontalHeaderLabels(
            ['Kitap ID', 'Kitap Adı', 'Kitap Türü', 'Yazar', 'Yayın Evi', 'Geliş Tarihi'])
        self.depositBookTableWidget.horizontalHeader().setHighlightSections(True)
        self.depositBookTableWidget.horizontalHeader().setSortIndicatorShown(False)
        self.gridLayout_3.addWidget(self.depositBookTableWidget, 1, 0, 1, 3)
        # Deposit book table widget end

        # Deposit user table widget
        self.depositUserTableWidget = QtWidgets.QTableWidget(self.gridLayoutWidget)
        self.depositUserTableWidget.setStyleSheet("\n"
                                                  "background-color: rgb(215, 215, 215);\n"
                                                  "color: rgb(103, 103, 103);")
        self.depositUserTableWidget.setShowGrid(True)
        self.depositUserTableWidget.setGridStyle(QtCore.Qt.SolidLine)
        self.depositUserTableWidget.setColumnCount(3)
        self.depositUserTableWidget.setObjectName("depositUserTableWidget")
        self.depositUserTableWidget.rowCount()
        self.depositUserTableWidget.setHorizontalHeaderLabels(['Kullanıcı ID', 'İsim-Soyisim', 'Telefon Numarası'])
        self.depositUserTableWidget.horizontalHeader().setHighlightSections(True)
        self.depositUserTableWidget.horizontalHeader().setSortIndicatorShown(False)
        self.gridLayout_3.addWidget(self.depositUserTableWidget, 3, 0, 1, 3)
        # Deposit user table widget end

        self.dateEdit = QtWidgets.QDateEdit(self.gridLayoutWidget)
        self.dateEdit.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(42, 42, 42);")
        self.dateEdit.setObjectName("dateEdit")
        self.gridLayout_3.addWidget(self.dateEdit, 4, 1, 1, 2)
        self.depositDatePickBox = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.depositDatePickBox.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(42, 42, 42);")
        self.depositDatePickBox.setObjectName("depositDatePickBox")
        self.depositDatePickBox.addItem("")
        self.depositDatePickBox.addItem("")
        self.depositDatePickBox.addItem("")
        self.depositDatePickBox.addItem("")
        self.gridLayout_3.addWidget(self.depositDatePickBox, 5, 1, 1, 2)
        self.depositUserSearchButton = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.depositUserSearchButton.setObjectName("depositUserSearchButton")
        self.gridLayout_3.addWidget(self.depositUserSearchButton, 2, 2, 1, 1)
        self.depositAddButton = QtWidgets.QPushButton(self.groupBox)
        self.depositAddButton.setGeometry(QtCore.QRect(260, 720, 122, 23))
        self.depositAddButton.setStyleSheet("background-color: rgb(152, 152, 152);\n"
"color: rgb(53, 53, 53);")
        self.depositAddButton.setObjectName("depositAddButton")

        self.getDepositUsers()
        self.getDepositBooks()

        self.lineEdit_2.returnPressed.connect(self.getSearchBook)
        self.depositUserNameEdit.returnPressed.connect(self.getSearchUser)

        self.depositAddButton = QtWidgets.QPushButton(self.groupBox)
        self.depositAddButton.setGeometry(QtCore.QRect(260, 720, 122, 23))
        self.depositAddButton.setStyleSheet("background-color: rgb(152, 152, 152);\n"
                                            "color: rgb(53, 53, 53);")
        self.depositAddButton.setObjectName("depositAddButton")
        self.depositAddButton.clicked.connect(self.depositAdd)

        self.retranslateUi(depositAdd)
        QtCore.QMetaObject.connectSlotsByName(depositAdd)

    def retranslateUi(self, depositAdd):
        _translate = QtCore.QCoreApplication.translate
        depositAdd.setWindowTitle(_translate("depositAdd", "Dialog"))
        self.groupBox.setTitle(_translate("depositAdd", "Emanet Kitap Ekle"))
        self.label.setText(_translate("depositAdd", "Kitap Adı:"))
        self.label_2.setText(_translate("depositAdd", "Ödünç Alanın Adı:"))
        self.label_4.setText(_translate("depositAdd", "Kaç Gün Ödünç Verilecek:"))
        self.label_3.setText(_translate("depositAdd", "Ödünç Alınan Tarih:"))
        self.depositBookSearchButton.setText(_translate("depositAdd", "Ara"))
        self.depositDatePickBox.setItemText(0, _translate("depositAdd", "Seçiniz..."))
        self.depositDatePickBox.setItemText(1, _translate("depositAdd", "15 Gün"))
        self.depositDatePickBox.setItemText(2, _translate("depositAdd", "30 Gün"))
        self.depositDatePickBox.setItemText(3, _translate("depositAdd", "60 Gün"))
        self.depositUserSearchButton.setText(_translate("depositAdd", "Ara"))
        self.depositAddButton.setText(_translate("depositAdd", "Emanet Ekle"))
