# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

from UI_Layer import bookOperations, depositOperations, userOperationss


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(587, 395)
        MainWindow.setStyleSheet("background-color: rgb(49, 49, 49);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(9, 9, 571, 381))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.groupBox = QtWidgets.QGroupBox(self.horizontalLayoutWidget)
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.userOp = QtWidgets.QPushButton(self.groupBox)
        self.userOp.setGeometry(QtCore.QRect(60, 210, 141, 121))
        self.userOp.setStyleSheet("background-color: rgb(140, 140, 140);\n"
"font: 9pt \"Microsoft Sans Serif\";")
        self.userOp.setObjectName("userOp")
        self.libraryOp = QtWidgets.QPushButton(self.groupBox)
        self.libraryOp.setGeometry(QtCore.QRect(210, 210, 141, 121))
        self.libraryOp.setStyleSheet("background-color: rgb(148, 148, 148);\n"
"font: 9pt \"Microsoft Sans Serif\";")
        self.libraryOp.setObjectName("libraryOp")
        self.depositOp = QtWidgets.QPushButton(self.groupBox)
        self.depositOp.setGeometry(QtCore.QRect(360, 210, 141, 121))
        self.depositOp.setStyleSheet("background-color: rgb(148, 148, 148);\n"
"font: 9pt \"Microsoft Sans Serif\";")
        self.depositOp.setObjectName("depositOp")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(210, 50, 141, 51))
        self.label.setStyleSheet("font: 63 28pt \"Bahnschrift SemiBold\";\n"
"color: rgb(211, 211, 211);")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(160, 100, 251, 41))
        self.label_2.setStyleSheet("color: rgb(177, 177, 177);\n"
"font: 25 18pt \"Bahnschrift Light\";")
        self.label_2.setObjectName("label_2")

        self.userOp.raise_()
        self.libraryOp.raise_()
        self.depositOp.raise_()

        self.horizontalLayout.addWidget(self.groupBox)
        MainWindow.setCentralWidget(self.centralwidget)
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.libraryOp.clicked.connect(self.getBookOperations)
        self.userOp.clicked.connect(self.getUserOperations)
        self.depositOp.clicked.connect(self.getDepositOperations)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.userOp.setText(_translate("MainWindow", "Kullanıcı İşlemleri"))
        self.libraryOp.setText(_translate("MainWindow", "Kitap İşlemleri"))
        self.depositOp.setText(_translate("MainWindow", "Emanet İşlemleri"))
        self.label.setText(_translate("MainWindow", "KOLKTP"))
        self.label_2.setText(_translate("MainWindow", "Kolezyum Kütüphanesi"))

    def getBookOperations(self):
        dialog = QtWidgets.QDialog()
        dialog.ui = bookOperations.Ui_bookDialog()
        dialog.ui.setupUi(dialog)
        dialog.exec_()
        dialog.show()
    def getUserOperations(self):
        dialog = QtWidgets.QDialog()
        dialog.ui = userOperationss.Ui_userDialog()
        dialog.ui.setupUi(dialog)
        dialog.exec_()
        dialog.show()
    def getDepositOperations(self):
        dialog = QtWidgets.QDialog()
        dialog.ui = depositOperations.Ui_depositDialog()
        dialog.ui.setupUi(dialog)
        dialog.exec_()
        dialog.show()


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    mainUi = Ui_MainWindow()
    mainUi.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
