# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'userUpdatePage.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_userUpdatePage(object):
    def setupUi(self, userUpdatePage):
        userUpdatePage.setObjectName("userUpdatePage")
        userUpdatePage.resize(543, 268)
        userUpdatePage.setStyleSheet("background-color: rgb(49, 49, 49);")
        self.groupBox = QtWidgets.QGroupBox(userUpdatePage)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 521, 251))
        self.groupBox.setStyleSheet("color: rgb(190, 190, 190);\n"
"font: 9pt \"MS Shell Dlg 2\";")
        self.groupBox.setObjectName("groupBox")
        self.gridLayoutWidget = QtWidgets.QWidget(self.groupBox)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 20, 501, 171))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 3, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 4, 0, 1, 1)
        self.oldNameEdit = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.oldNameEdit.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(42, 42, 42);")
        self.oldNameEdit.setText("")
        self.oldNameEdit.setObjectName("oldNameEdit")
        self.gridLayout.addWidget(self.oldNameEdit, 3, 2, 1, 1)
        self.oldPhoneEdit = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.oldPhoneEdit.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(42, 42, 42);")
        self.oldPhoneEdit.setText("")
        self.oldPhoneEdit.setObjectName("oldPhoneEdit")
        self.gridLayout.addWidget(self.oldPhoneEdit, 4, 2, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 6, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 5, 0, 1, 1)
        self.newPhoneEdit = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.newPhoneEdit.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(42, 42, 42);")
        self.newPhoneEdit.setObjectName("newPhoneEdit")
        self.gridLayout.addWidget(self.newPhoneEdit, 6, 2, 1, 1)
        self.newNameEdit = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.newNameEdit.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(42, 42, 42);")
        self.newNameEdit.setObjectName("newNameEdit")
        self.gridLayout.addWidget(self.newNameEdit, 5, 2, 1, 1)
        self.updateButton = QtWidgets.QPushButton(self.groupBox)
        self.updateButton.setGeometry(QtCore.QRect(210, 200, 101, 41))
        self.updateButton.setStyleSheet("background-color: rgb(152, 152, 152);\n"
"color: rgb(53, 53, 53);")
        self.updateButton.setObjectName("updateButton")

        self.retranslateUi(userUpdatePage)
        QtCore.QMetaObject.connectSlotsByName(userUpdatePage)

    def retranslateUi(self, userUpdatePage):
        _translate = QtCore.QCoreApplication.translate
        userUpdatePage.setWindowTitle(_translate("userUpdatePage", "Dialog"))
        self.groupBox.setTitle(_translate("userUpdatePage", "Kullanıcı Güncelleme"))
        self.label.setText(_translate("userUpdatePage", "Eski isim-soyisim:"))
        self.label_2.setText(_translate("userUpdatePage", "Eski telefon no:"))
        self.label_4.setText(_translate("userUpdatePage", "Yeni telefon no:"))
        self.label_3.setText(_translate("userUpdatePage", "Yeni isim-soyisim:"))
        self.updateButton.setText(_translate("userUpdatePage", "Güncelle"))
